os: osx
osx_image: xcode11.2
language: swift

before_install:
  - chmod +x install_swiftlint.sh

install:
  - ./install_swiftlint.sh

script:
  - xcodebuild build test -project ./FSLocator.xcodeproj -scheme "FSLocator" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.2.2,name=iPhone 11" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
